### ISSUE TITLE
Controleren op de uniciteit van titels, samenvatting & IDs

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#10]

**Comment by gerardnienhuis** [comment]
Hier zijn 5 controle's mogelijk, waardoor misschien dit issue beter in 6 delen uiteen gesplitst kan worden. Dan hoeven deze ook niet allemaal tegelijk opgeleverd te worden. Testen zijn:
Er staan in het rapport 4 verschillende id's (1 nummer en 3 uuid's). Deze moeten allemaal uniek zijn. Verder is de eis dat titels en samenvattingen uniek moeten zijn.
Tekst in "controle_totaal" moet worden:
"ID A is niet uniek" waarbij A de naam van de header is (4 verschillende controles).
"Titel is niet uniek"
"Samenvatting is niet uniek"

**Comment by luclecq** [comment]
Focus op kolom voor uniciteit IDs:
- identification

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, issue kan gesloten
