### ISSUE TITLE
Controleren op verboden karakters in titel en samenvatting

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#11]

**Comment by gerardnienhuis** [comment]
Eerst graag kijken titel en samenvatting. Overwegen tzt om alle vrije velden te controleren, dus ook organisatienaam enz. Nu niet uitvoeren. Wordt opgenomen in issue ...

**Comment by luclecq** [comment]
> Eerst graag kijken titel en samenvatting. Overwegen tzt om alle vrije velden te controleren, dus ook organisatienaam enz. Nu niet uitvoeren. Wordt opgenomen in issue ...

Het vervolg hierop is #25.

**Comment by luclecq** [comment]
Deze wens is toegevoegd, zie release 0.5.

**Comment by luclecq** [comment]
Na testen blijken datasets soms onterecht de melding "fout teken in titel" te krijgen, omdat er geen rekening wordt gehouden met de context waarin verboden karakters voorkomen. Dit strookt niet met de uitzondering in de invulinstructie, namelijk dat een dubbele punt is toegestaan bij bestanden waar dat gebruikelijk is (vb. topografische schaal 1 : 10 000).

In overleg aanmaken van nieuw issue, of accepteren dat deze analyse soms foutpositief is.

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, er staat aangegeven met x dat er een verboden teken is. Steeksproefsgewijs getest, klopt ook echt. issue kan gesloten.

extra wensen opgenomen hierover bij https://github.com/luclecq/metadatakwaliteit/issues/28
