### ISSUE TITLE
Controleren op eenduidig spelling van contactpersonen

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#13]

**Comment by gerardnienhuis** [comment]
Dat lijkt me een hele lastige. Je kan wel testen of emailadressen van contactpersonen wel correct zijn (zie issue ...) maar namen van contactpersonen? Je zou kunnen testen of achternamen op 2 of 3 manieren geschreven zijn (Nienhuis en Ninhuis of Nienhuijs) maar wat levert dat op? Mogelijk bestaan alle drie deze namen wel. Je kan wel iets met kansen doen... Bijvoorbeeld als er 2 keer Nienhuis voorkomt. De ene keer J.G. Nienhuis en de andere keer G. Nienhuis. Zo'n controle is wel zinvol, misschien. Tekst in "controle_totaal" wordt dan "Naam contactpersoon mogelijk fout".

**Comment by luclecq** [comment]
Ivm impact hoog, verschoven naar latere milestone.

**Comment by luclecq** [comment]
In overleg verschoven naar milestone 2.0

**Comment by luclecq** [comment]
Tips van Martin, ter overweging:
spaties negeren
gevoeligheid voor hoofdletters
emails zonder naam (en vv)

**Comment by luclecq** [comment]
Functie is toegevoegd, maar met een aanvullende kanttekening:

Als er een naam met meerdere geassocieerde emails (of vv) is gevonden, worden niet beide records gesignaleerd. Één email-naam combinatie is immers wel valide, maar het script weet niet welke. 

Graag in overleg:
Is het dan de taak van de beheerder om die naam en/of email verder te controleren op afwijkingen?
Is het zinvol om alle records, waar een door deze controle gesignaleerde email en/of naam in voorkomt, aan te merken als fout?

**Comment by gerardnienhuis** [comment]
Goed idee om dit als waarschuwing te kenmerken

**Comment by gerardnienhuis** [comment]
werkt naar tevredenheid, issue kan gesloten
