### ISSUE TITLE
Controleren op correcte combinatie van updatefrequentie en laatste_wijziging_bestandsbeschrijving

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#15]

**Comment by gerardnienhuis** [comment]
Mijn voorstel zou zijn om eerst te kijken naar de updatefrequentie van bestand en samenvatting. Als er staat dat de frequentie 1 jaar is, en alle beide die frequenties zijn ouder dan een jaar, dan vermelden in "controle_totaal" als "verouderd bestand".

**Comment by luclecq** [comment]
In overleg met Gerard besloten om te verplaatsen naar milestone 0.6.

**Comment by luclecq** [comment]
In overleg:
- jaarlijks

Bij tijd over:
- 2-jaarlijks
- halfjaarlijks

**Comment by luclecq** [comment]
Is getest, blijkt goed te werken. Issue kan gesloten.
