### ISSUE TITLE
Volgorde van waarschuwingen en fouten 

### ISSUE THREAD

**Issue by gerardnienhuis** [luclecq/metadatakwaliteit#17]
De wens is om een logische volgorde aan te brengen in de vermelding van fouten en waarschuwingen die terecht gaan komen in "controle_totaal". De fout met de grootste impact vooraan, daarna de ene na grootste erachter enz.. 

Heb je dus 4 fouten en 1 waarschuwing, dan wordt de inhoud van "controle_totaal" bijvoorbeeld:

fout A, fout B, fout C, fout D en waarschuwing X

waarbij A dus een grotere fout is, dan B. B groter dan C enz...

**Comment by luclecq** [comment]
Deze functionaliteit is toegevoegd (gerelateerd aan #8). De volgorde graag in overleg vaststellen.

**Comment by luclecq** [comment]
Is getest, volgorde blijkt niet te zijn zoals verwacht. Verschoven naar 0.7.

**Comment by gerardnienhuis** [comment]
kolommen getest, werkt goed,  issue kan gesloten
