### ISSUE TITLE
script zo maken dat input en output pad ook in py staan

### ISSUE THREAD

**Issue by gerardnienhuis** [luclecq/metadatakwaliteit#19]
Wens is dat python script ook zonder bat file te gebruiken is, dus met opgeven van input en output pad in python

**Comment by luclecq** [comment]
Bestandspaden kunnen nu via 2 manieren worden ingevoerd: via opdrachtprompt/batchbestand en in het script zelf als 'lokaal bestandspad'.  Bij beide manieren wordt de input gevalideerd.

Wordt meegeleverd in milestone 0.5.

**Comment by gerardnienhuis** [comment]
Test is succesvol afgerond, wat betreft op uitvoering op laptop van mij. Maar we hebben ontdekt dat bij de omgevingen van Overijssel niet altijd python op C te vinden is. Op fat clients mogelijk wel. Zie issue ... Dit issue kan worden gesloten.

**Comment by gerardnienhuis** [comment]
zie verder https://github.com/luclecq/metadatakwaliteit/issues/27
