### ISSUE TITLE
Script opstarten via command prompt op installatie van Overijssel

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#2]

**Comment by gerardnienhuis** [comment]
is nog niet getest, dus opnieuw geopend

**Comment by gerardnienhuis** [comment]
zojuist getest op omgeving Overijssel. Regel uit batch file gehaald en gestart op Opdrachtprompt. Blijkt goed te werken: outputfile wordt gemaakt en bevat zinvolle tekst.

issue kan gesloten.
