### ISSUE TITLE
Foutmelding onjuist bij inputfile die niet bestaat

### ISSUE THREAD

**Issue by gerardnienhuis** [luclecq/metadatakwaliteit#20]
Als de inputfile niet bestaat, dan krijg ik een verkeerde foutmelding. Het lijkt wel alsof de waarschuwing nu is, dat het pythonscripts niet bestaat. Dat bestaat echter wel, zie bijgevoegd plaatje.

**Comment by luclecq** [comment]
Het lijkt erop dat je een script opent vanaf de D-schijf (vermoedelijk een usb-stick). Je verkenner op de afbeelding laat een pythonscript zien dat op de H-schijf staat. 

Probeer om het volgende pad te gebruiken in het batchbestand: H:\AAA_MIJN_DOCUMENTEN\project_2018\Luc\test_04\rapport_geodata_analyse.py

**Comment by gerardnienhuis** [comment]
is getest: paden waren verkeerd in batch file gezet, wordt mogelijk tzt aangepast, zie issue #22 

werkt goed nadat paden zijn aangepast, issue kan gesloten
