### ISSUE TITLE
Output bevat 1 record minder dan input

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#23]
Vaak zorgt het schrijven van de laatste record voor problemen.
Tip: gebruik input van 1 record, daarna van 10 records

**Comment by luclecq** [comment]
Bug blijkt niet te reproduceren: getest met 1, 10 en 1069 records. Aantal records van input- en outputbestand blijft gelijk.

**Comment by gerardnienhuis** [comment]
probleem blijkt niet meer te bestaan. Getest met file van 1077 regels input, levert zelfde aantal regels output. Filestructuur is ook normaal. Werkt goed dus, issue kan gesloten.
