### ISSUE TITLE
Controleren op alle verboden karakters

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#25]
Wens is om in elk veld te controleren op verboden karakters, zoals beschreven in de invulinstructie. Dit is in het verlengde van #11.

**Comment by luclecq** [comment]
In overleg is issue opgenomen in 0.6. Bij weinig tijd wordt issue verschoven naar milestone 0.7.

**Comment by luclecq** [comment]
In overleg blijft issue in 0.6. Wordt wel minder elegant geprogrammeerd.
Consequentie is dat de oplossing niet dynamisch en compact is: nieuwe kolommen in de input vereisen handmatige aanpassingen. Zie ook issue #30.

**Comment by gerardnienhuis** [comment]
blijkt zeer goed: via steekproeven gecontroleerd. issue kan gesloten
nb: het is handiger om niet alles te testen, zie verder issue ...
