### ISSUE TITLE
Genereren van tekstbestand met bevindingen van de analyse (run file)

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#26]
Wens is om een platte tekst-bestand te laten genereren voor elke keer dat het script is uitgevoerd. De inhoud van deze run file is vergelijkbaar met wat er na afloop van de analyse naar de console wordt geprint.
Denk aan de volgende kenmerken: 
- timestamp in de bestandsnaam, bv. "run_script_20181126_0955.txt"
- bestandsnamen van de input en output
- volledige begin- en eindtijd
- aantal gelezen regels
- aantal datasets met een melding

**Comment by luclecq** [comment]
Graag in overleg:
- Wens of luxe?
- Milestone?
- Ook run file genereren bij een vroegtijdige beëindiging van het script?
- Melding over welke bestandsnamen zijn gebruikt (lokaal of via opdrachtprompt/batchbestand)?

**Comment by luclecq** [comment]
In overleg labels en milestones toegevoegd.

**Comment by luclecq** [comment]
Na overleg:

> Ook run file genereren bij een vroegtijdige beëindiging van het script?

Ja

> Melding over welke bestandsnamen zijn gebruikt (lokaal of via opdrachtprompt/batchbestand)?

Ja

**Comment by luclecq** [comment]
Advies: log file stukje voor stukje opbouwen. Is nog niet geïmplementeerd. Verschoven naar 1.0.

**Comment by gerardnienhuis** [comment]
Runfile werkt al wel goed, wordt aan einde gemaakt en weggeschreven. Opbouw in stukjes om crashes te laten zien is ander issue. Dit issue kan dus gesloten
