### ISSUE TITLE
Verboden tekens ook in rapport opnemen

### ISSUE THREAD

**Issue by gerardnienhuis** [luclecq/metadatakwaliteit#28]
Niet alleen maar aangeven in rapport dat er een verboden teken is, maar ook het teken zelf in een aparte kolom opnemen. Bij meerdere verboden tekens ze allemaal opnemen, gescheiden door spatie.

**Comment by luclecq** [comment]
In overleg naar 0.6.

**Comment by luclecq** [comment]
Is uitvoerig getest, blijkt niet consequent te werken. Toegevoegd aan 0.7.

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, issue kan gesloten
