### ISSUE TITLE
Lege waarden vervangen door zinvolle vulling en x vervangen door ja

### ISSUE THREAD

**Issue by gerardnienhuis** [luclecq/metadatakwaliteit#29]
Wens is dat bij controle_totaal er "goed" wordt ingevuld als er geen fouten worden gevonden. Ook nee invullen als bij de afzonderlijke testen niets is gevonden. Is er wel een fout gevonden, dan niet x neerzetten maar "ja".

**Comment by luclecq** [comment]
Is getest, blijkt goed te werken. Issue kan gesloten worden.
