### ISSUE TITLE
Volgorde kolommen outputfile vergelijkbaar met inputfile (met extra eerste kolom "controle_totaal")

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#3]

**Comment by gerardnienhuis** [comment]
Dit is wel heel belangrijk voor het goed kunnen interpreteren van de resultaten van de controles. Wens is om dit echt in een volgende versie uit te rollen. De alle kolommen vergelijkbaar met inputfile ook in outputfile, met in ieder geval 1 extra kolom helemaal aan begin: "controle_totaal".

**Comment by gerardnienhuis** [comment]
getest: zowel begin, midden als einde kolommen kloppen. werkt goed, issue kan gesloten
