### ISSUE TITLE
Resultaten van scoreformulier meewegen in keuze voor issues in 0.7

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#31]
Het idee is om de focus op bepaalde analyses af te laten hangen van de resultaten van het prioriteitenonderzoekje onder beheerders.

**Comment by gerardnienhuis** [comment]
is al onderzocht. Niet nodig om analyseresultaten te veranderen. De controles die relevant zijn, die worden al uitgevoerd. Issue kan gesloten.
