### ISSUE TITLE
2 nieuwe controlekolommen: controle_fout en controle_waarschuwing.

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#32]
Wens is om op basis van controle_totaal (alle controles) twee ja/nee kolommen aan te maken. Een voor fouten en een voor minder belangrijke waarschuwingen.

VB:
bronmetadata afwezig? controle_fout = ja
datum voltooing bestand ouder dan updatefrequentie? controle_waarschuwing = ja

**Comment by luclecq** [comment]
Fout:
bronmetadata afwezig
fout teken in titel (rest)
verouderd bestand

Waarschuwing:
fout teken in samenvatting
fout teken in titel (‘ ; ,)
fout in spelling land

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, issue kan gesloten
