### ISSUE TITLE
zinvolle controle verboden tekens

### ISSUE THREAD

**Issue by gerardnienhuis** [luclecq/metadatakwaliteit#35]
controleren alleen op zinvolle velden als het over verboden tekens gaat.

zie ook

https://github.com/luclecq/metadatakwaliteit/issues/25

**Comment by gerardnienhuis** [comment]
zinvolle kolommen zijn:
titel
abstract
alle 6 organisatienamen (bv auteur_metadata_naam_organisatie)
alle 6 namen contactpersonen (bv auteur_metadata_naam_contactpersoon)

**Comment by luclecq** [comment]
> zinvolle kolommen zijn:
titel
abstract
alle 6 organisatienamen (bv auteur_metadata_naam_organisatie)
alle 6 namen contactpersonen (bv auteur_metadata_naam_contactpersoon)

De controle op verboden tekens wordt nu alleen op deze kolommen uitgevoerd. Ook worden er geen dubbele meldingen meer naar "controle_totaal" geschreven als er twee verschillende verboden karakters in één kolom gevonden zijn.

Gebruikerstest graag in overleg.
