### ISSUE TITLE
Controleren op lengte van titel en samenvatting

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#37]
Wens is om een waarschuwing te geven wanneer het aantal karakters buiten bepaalde grenswaarden vallen. Dit kan voor zowel titel als samenvatting.

**Comment by gerardnienhuis** [comment]
Als dit issue in productie is, dan zijn bijna alle controles geautomatiseerd. Wens is daarom om dit ook uit te werken. 

De grenzen zijn:

Fout: alleen als lengte samenvatting groter dan 2000 tekens is (tekst in controle_totaal is: "samenvatting te lang"

Waarschuwing: samenvatting lengte kleiner dan 100 (tekst is: "samenvatting kort"

Waarschuwing: titel lengte kleiner dan 10 (tekst is: "titel kort")

Waarschuwing: titel lengte groter dan 100 (tekst is: "titel lang")

**Comment by gerardnienhuis** [comment]
Lijkt niet goed te werken. samenvatting fout lengte wordt gevonden in aantal datasets waarvan lengte < 2000 is. 

lastig te controleren in huidige outputfile:

wens is 2 kolommen extra op te nemen


**1) kolomnaam:lengte_titel**
inhoud: lengte van aantal tekens in kolom title

nb: 
als lengte_titel is groter dan 10, dan
opnemen in controle_waarschuwing: "titel kort"

als lengte_titel is groter dan 100, dan
opnemen in controle_waarschuwing: "titel lang"


**2) kolomnaam:lengte_samenvatting**
inhoud: lengte van aantal tekens in kolom abstract

als lengte_samenvatting is kleiner dan 100, dan
opnemen in controle_waarschuwing: "samenvatting kort"

als lengte_samenvatting is groter dan 2000, dan
opnemen in controle_fout: "samenvatting te lang"

**Comment by gerardnienhuis** [comment]
1 fout gevonden bij testserie input121218.txt
(1 keer onjuiste foutmelding bij lengte samenvatting)

rest controles lijken wel goed te gaan

**Comment by luclecq** [comment]
Oorzaak: excel controleert aantal karakters anders dan spyder
Effect: onverwachte meldingen bij lengtes rondom grenswaarden (kantelpunt), vb. samenvatting van bijna 2000 tekens

In overleg met @gerardnienhuis:
Inhoudelijk worden deze datasets terecht aangemerkt als fout.

**Comment by gerardnienhuis** [comment]
Dit is blijkt goed te werken, extra spaties aan einde is geen probleem dat dit fout oplevert, is aan te passen in kader van gegevensbeheer. issue kan gesloten
