### ISSUE TITLE
3 verboden_teken_karakter kolommen voor titel, abstract en personen-/organisatienamen

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#38]
Wens is om het daadwerkelijke karakter dat een ja genereert in "fout_teken_titel", "fout_teken_samenvatting" of "fout_teken_namen" in een eigen "verboden_teken_karakter" kolom te plaatsen.

Dus:
verboden_teken_titel_karakter
verboden_teken_samenvatting_karakter
verboden_teken__namen_karakter

**Comment by luclecq** [comment]
Gerelateerd aan #17 en #25

**Comment by gerardnienhuis** [comment]
kolommen en inhoud blijken goed te werken, issue kan gesloten
