### ISSUE TITLE
Begrijpelijke beschrijvingen van foutmeldingen in "controle_totaal"

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#4]

**Comment by luclecq** [comment]
@gerardnienhuis geef mij dan alsjeblieft suggesties voor namen van foutmeldingen. Kan dit op basis van eerdere beschrijving uit Tableau?

**Comment by gerardnienhuis** [comment]
Bij iedere controle probeer ik ook in github te zetten wat de tekst moet worden in "controle_totaal". Hierdoor is de controle beschreven en meteen ook het bedoelde (gewenste) resultaat. Zou dat gaan werken?

**Comment by gerardnienhuis** [comment]
Na overleg blijkt dit te kunnen werken, issue kan gesloten.
