### ISSUE TITLE
Verschillende meldingen printen tijdens runtime

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#5]
Meldingen:
Aantal gelezen regels
Starttijd
Eindtijd
"naam programma, versie, gemaakt door ..."

Meldingen naar scherm allemaal gescheiden boven en onder door witregel

**Comment by gerardnienhuis** [comment]
getest in Overijssel, op infra van Overijssel. Blijkt goed leesbaar te zijn wat op scherm komt (in dosbox). Issue kan gesloten
