### ISSUE TITLE
Per foutmelding een losse kolom toevoegen

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#7]

**Comment by gerardnienhuis** [comment]
Niet dringend nodig. Je kan overwegen om echte fouten te scheiden van waarschuwingen. Titel kort is waarschuwing. Bronmetadata afwezig is fout. Het kan nut hebben om allemaal extra kolommen te maken, maar heb daar nog geen ervaring mee. Ook te overwegen: bij "verkeerde karakters" in titel of samenvatting dan de gevonden verkeerde karakters in een aparte kolom opnemen. Zijn er meer, dan scheiden door spaties.

Bijvoorbeeld: kolom "fout karakter titel" toevoegen.
Inhoud voorbeeld 1: "@" (er is maar 1 verkeerd karakter gevonden, en wel @) 
inhoud voorbeeld 2: "@ # @ @ & * % % @ !" (er zijn meerdere verkeerde karakters gevonden)

**Comment by luclecq** [comment]
Losse kolommen zijn toegevoegd voor de analyses in release 0.5. In overleg kan dit worden doorgezet voor de resterende controles.

**Comment by luclecq** [comment]
> Ook te overwegen: bij "verkeerde karakters" in titel of samenvatting dan de gevonden verkeerde karakters in een aparte kolom opnemen. Zijn er meer, dan scheiden door spaties.
> 
> Bijvoorbeeld: kolom "fout karakter titel" toevoegen.
> Inhoud voorbeeld 1: "@" (er is maar 1 verkeerd karakter gevonden, en wel @)
> inhoud voorbeeld 2: "@ # @ @ & * % % @ !" (er zijn meerdere verkeerde karakters gevonden)

Deze functionaliteit is niet opgeleverd in release 0.5. In overleg moet besloten worden of deze suggestie een eigen issue krijgt voor een volgende milestone, vanwege de hoge verwachte impact.

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, er staat met x aangegeven dat er een bepaalde fout is. Getest steeksproefsgewijs, klopt ook wat er is ingevuld, issue kan gesloten.
