### ISSUE TITLE
Bij meerdere foutmeldingen per dataset de meldingen achter elkaar toevoegen in "rapport_totaal"

### ISSUE THREAD

**Issue by luclecq** [luclecq/metadatakwaliteit#8]

**Comment by gerardnienhuis** [comment]
Wens is om all foutmeldingen en waarschuwingen in "controle_totaal" te laten beginnen met kleine letters, en te scheiden door komma met spatie. Je krijgt dan bijvoorbeeld: 

bronmetadata afwezig, titel niet uniek
of 
titel niet uniek, samenvatting niet uniek, bronmetadata afwezig

**Comment by luclecq** [comment]
Deze wens is toegevoegd, zie ook #17.

**Comment by gerardnienhuis** [comment]
getest, blijkt goed te werken, steeksproefsgewijs getest, gefilterd met bronmetadata aan en afwezig, werkt goed, issue kan gesloten.
